// Code generated by "stringer -type ID -trimprefix ID"; DO NOT EDIT.

package store

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unresolvedEntityID-0]
	_ = x[IDID - -1]
	_ = x[IDIdent - -2]
	_ = x[IDType - -3]
	_ = x[IDCompositeComponents - -4]
	_ = x[IDCardinality - -5]
	_ = x[IDUnique - -6]
	_ = x[IDIndexed - -7]
	_ = x[IDDoc - -8]
	_ = x[IDTxCommitTime - -9]
	_ = x[IDCardinalityOne - -10]
	_ = x[IDCardinalityMany - -11]
	_ = x[IDTypeString - -511]
	_ = x[IDTypeBoolean - -512]
	_ = x[IDTypeInt64 - -513]
	_ = x[IDTypeInt32 - -514]
	_ = x[IDTypeInt16 - -515]
	_ = x[IDTypeInt8 - -516]
	_ = x[IDTypeFloat64 - -517]
	_ = x[IDTypeFloat32 - -518]
	_ = x[IDTypeDecimal - -519]
	_ = x[IDTypeTimestamp - -520]
	_ = x[IDTypeDate - -521]
	_ = x[IDTypeRef - -522]
	_ = x[IDTypeBinary - -523]
	_ = x[IDTypeUUID - -524]
	_ = x[IDTypeULID - -525]
	_ = x[IDTypeComposite - -526]
}

const (
	_ID_name_0 = "TypeCompositeTypeULIDTypeUUIDTypeBinaryTypeRefTypeDateTypeTimestampTypeDecimalTypeFloat32TypeFloat64TypeInt8TypeInt16TypeInt32TypeInt64TypeBooleanTypeString"
	_ID_name_1 = "CardinalityManyCardinalityOneTxCommitTimeDocIndexedUniqueCardinalityCompositeComponentsTypeIdentIDunresolvedEntityID"
)

var (
	_ID_index_0 = [...]uint8{0, 13, 21, 29, 39, 46, 54, 67, 78, 89, 100, 108, 117, 126, 135, 146, 156}
	_ID_index_1 = [...]uint8{0, 15, 29, 41, 44, 51, 57, 68, 87, 91, 96, 98, 116}
)

func (i ID) String() string {
	switch {
	case -526 <= i && i <= -511:
		i -= -526
		return _ID_name_0[_ID_index_0[i]:_ID_index_0[i+1]]
	case -11 <= i && i <= 0:
		i -= -11
		return _ID_name_1[_ID_index_1[i]:_ID_index_1[i+1]]
	default:
		return "ID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
