name: Build

on:
  workflow_call: {}

env:
  GO_VERSION: "1.21.0"

jobs:
  unit-test:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
