name: CI

on:
  push:
    branches:
      - main

jobs:
  call-build:
    uses: ./.github/workflows/build.yml

  call-integration-tests:
    uses: ./.github/workflows/integration-tests.yml
    # Only run if basic build is successful.
    needs:
      - call-build
